apiVersion: v1
kind: Namespace
metadata:
  name: awesome-role-testing-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-pods-and-services-role
  namespace: awesome-role-testing-namespace
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-pods-and-services-rolebinding
  namespace: awesome-role-testing-namespace
roleRef:
 apiGroup: rbac.authorization.k8s.io/v1
 kind: Role
 name: view-pods-and-services-role
subjects:
- apiGroup: rbac.authorization.k8s.io/v1
  kind: Group
  name: monitoring
