apiVersion: v1
kind: Namespace
metadata:
  name: awesome-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-deployment
  namespace: awesome-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: hello-service
      annotations:
        example.org/deployment-version: "1.1"
        kubernetes.io/change-cause: "Meaningful information about the change cause goes here"
    spec: 
      containers:
      - name: hello-service-container
        image: antsinmyey3sjohnson/hello-container-service:1.0
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
      - name: tools
        image: registry.access.redhat.com/rhel7/rhel-tools:latest
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "tail -f /dev/null"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
    
      
    
