apiVersion: v1
kind: Namespace
metadata:
  name: my-configmap-exploration-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cool-configmap
  namespace: my-configmap-exploration-namespace
data:
  someVar: someValue
  someOtherVar: someOtherValue
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-configmap-exploration-namespace
  labels:
    app: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels: 
        app: my-deployment
    spec:
      containers:
      - name: my-configmap-consuming-container
        image: registry.access.redhat.com/rhel7/rhel-tools
        command:
          - "/bin/bash"
          - "-c"
        args:
          - "while true; do
               echo \"Read from env variable: ${MY_ENV_VARIABLE}\";
               echo \"Read from file created by mounting ConfigMap: $(cat /config/someOtherVar)\";
               sleep 10;
             done"
        env:
        - name: MY_ENV_VARIABLE
          valueFrom:
            configMapKeyRef:
              name: my-cool-configmap
              key: someVar
        volumeMounts:
          - mountPath: /config
            name: config-volume
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits: 
            cpu: "200m"
            memory: "512Mi"
      volumes:
      - name: config-volume
        configMap:
          name: my-cool-configmap
      
          