apiVersion: v1
kind: Namespace
metadata:
  name: awesome-namespace
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-service
  namespace: awesome-namespace
spec:
  selector:
    matchLabels:
      app: hello-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: hello-service-container
        image: antsinmyey3sjohnson/hello-container-service:1.0
        ports:
        - containerPort: 8081
          protocol: TCP
          